version: "3.8"

services:
  app:
    image: app:latest
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - "./:/code"
    ports:
      - "8000:8000"
    networks:
      - chess
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: db
    hostname: localhost
    env_file:
      - .env
    volumes:
       - pgdata:/var/lib/postgresql/data
    networks:
      - chess
    ports:
      - "5432:5432"

volumes:
  pgdata:

networks:
  chess:
    driver: bridge
  