version: "3.8"

services:
  app:
    image: app:latest
    networks:
      - app_network
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - "./:/code"
    ports:
      - "8000:8000"

networks:
  app_network:

  